name: telita_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_tv_media3:
    path: ./plugins/flutter_tv_media3
  http: ^1.6.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  crypto: ^3.0.3
  qr_flutter: ^4.1.0
  lottie: ^3.3.3
  window_manager: ^0.4.3
  flutter_staggered_animations: ^1.1.1
  fvp: ^0.37.3
  video_player: ^2.11.1
  flutter_svg: ^2.0.10+1
  flutter_colorpicker: ^1.1.0
  file_picker: ^8.0.0+1
  path_provider: ^2.1.4
  ffi: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/pfps/
    - assets/logos/



